table Personas
	measure 'Plantilla al cierre' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN COALESCE ( COUNTROWS ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) ) ), 0 )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Plantilla al inicio' =
			VAR Corte = MIN ( Calendario[Fecha] ) - 1
			RETURN COALESCE ( COUNTROWS ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) ) ), 0 )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Altas del periodo' =
			VAR Inicio = MIN ( Calendario[Fecha] )
			VAR Fin = MAX ( Calendario[Fecha] )
			RETURN COALESCE ( COUNTROWS ( FILTER ( Personas, NOT ISBLANK ( Personas[FechaAlta] ) && Personas[FechaAlta] >= Inicio && Personas[FechaAlta] <= Fin ) ), 0 )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Bajas del periodo' =
			VAR Inicio = MIN ( Calendario[Fecha] )
			VAR Fin = MAX ( Calendario[Fecha] )
			RETURN COALESCE ( COUNTROWS ( FILTER ( Personas, NOT ISBLANK ( Personas[FechaBajaEmpresa] ) && Personas[FechaBajaEmpresa] >= Inicio && Personas[FechaBajaEmpresa] <= Fin ) ), 0 )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Dias del periodo' =
			DATEDIFF ( MIN ( Calendario[Fecha] ), MAX ( Calendario[Fecha] ), DAY ) + 1
		formatString: #,0
		displayFolder: Indicadores

	measure 'Exposicion persona dias' =
			VAR Inicio = MIN ( Calendario[Fecha] )
			VAR Fin = MAX ( Calendario[Fecha] )
			RETURN COALESCE ( SUMX ( Personas, VAR Desde = MAX ( Inicio, Personas[FechaAlta] ) VAR Hasta = MIN ( Fin, COALESCE ( Personas[FechaBajaEmpresa], Fin + 1 ) - 1 ) RETURN MAX ( 0, INT ( Hasta - Desde ) + 1 ) ), 0 )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Plantilla media diaria' =
			DIVIDE ( [Exposicion persona dias], [Dias del periodo] )
		formatString: #,0.0
		displayFolder: Indicadores

	measure 'Cambio neto' =
			[Altas del periodo] - [Bajas del periodo]
		formatString: +#,0;-#,0;0
		displayFolder: Indicadores

	measure 'Crecimiento neto %' =
			DIVIDE ( [Cambio neto], [Plantilla al inicio] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Rotacion del periodo %' =
			DIVIDE ( [Bajas del periodo], [Plantilla media diaria] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Rotacion anual %' =
			[Rotacion del periodo %]
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Compatibilidad; no anualizada

	measure 'Retencion cohorte inicial %' =
			VAR Inicio = MIN ( Calendario[Fecha] )
			VAR Fin = MAX ( Calendario[Fecha] )
			VAR Cohorte = FILTER ( Personas, Personas[FechaAlta] < Inicio && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] >= Inicio ) )
			RETURN DIVIDE ( COUNTROWS ( FILTER ( Cohorte, ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Fin ) ), COUNTROWS ( Cohorte ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Bajas antes de un ano' =
			VAR Inicio = MIN ( Calendario[Fecha] )
			VAR Fin = MAX ( Calendario[Fecha] )
			RETURN COALESCE ( COUNTROWS ( FILTER ( Personas, NOT ISBLANK ( Personas[FechaBajaEmpresa] ) && Personas[FechaBajaEmpresa] >= Inicio && Personas[FechaBajaEmpresa] <= Fin && Personas[FechaBajaEmpresa] < EDATE ( Personas[FechaAlta], 12 ) ) ), 0 )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Salario medio' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN AVERAGEX ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) && NOT ISBLANK ( Personas[SalarioAnual] ) && Personas[SalarioAnual] > 0 ), Personas[SalarioAnual] )
		formatString: #,0 "€"
		displayFolder: Indicadores

	measure 'Salario mediano' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN MEDIANX ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) && NOT ISBLANK ( Personas[SalarioAnual] ) && Personas[SalarioAnual] > 0 ), Personas[SalarioAnual] )
		formatString: #,0 "€"
		displayFolder: Indicadores

	measure 'Coste salarial anual' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN SUMX ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) && NOT ISBLANK ( Personas[SalarioAnual] ) && Personas[SalarioAnual] > 0 ), Personas[SalarioAnual] )
		formatString: #,0 "€"
		displayFolder: Indicadores

	measure 'Personas con salario' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN COALESCE ( COUNTROWS ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) && NOT ISBLANK ( Personas[SalarioAnual] ) && Personas[SalarioAnual] > 0 ) ), 0 )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Cobertura salarial %' =
			DIVIDE ( [Personas con salario], [Plantilla al cierre] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Edad media' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN AVERAGEX ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) && NOT ISBLANK ( Personas[FechaNacimiento] ) && Personas[FechaNacimiento] <= Corte ), VAR Nacimiento = Personas[FechaNacimiento] RETURN YEAR ( Corte ) - YEAR ( Nacimiento ) - IF ( FORMAT ( Corte, "MMdd" ) < FORMAT ( Nacimiento, "MMdd" ), 1, 0 ) )
		formatString: #,0.0
		displayFolder: Indicadores

	measure 'Cobertura nacimiento %' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN DIVIDE ( COUNTROWS ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) && NOT ISBLANK ( Personas[FechaNacimiento] ) && Personas[FechaNacimiento] <= Corte ) ), [Plantilla al cierre] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Lectura de calidad' =
			VAR Base = [Plantilla al cierre]
			VAR Salarios = Base - [Personas con salario]
			VAR Nacimientos = ROUND ( Base * ( 1 - [Cobertura nacimiento %] ), 0 )
			VAR Sexo = ROUND ( Base * ( 1 - [Cobertura sexo %] ), 0 )
			RETURN IF ( Base = 0, "Sin plantilla en el corte", IF ( Salarios + Nacimientos + Sexo = 0, "Campos analizados completos", "Hay campos por completar" ) )
		formatString: General
		displayFolder: Indicadores

	measure 'Plantilla por tramo de edad' =
			VAR Corte = MAX ( Calendario[Fecha] )
			VAR Desde = SELECTEDVALUE ( TramosEdad[Desde], 0 )
			VAR Hasta = SELECTEDVALUE ( TramosEdad[Hasta], 999 )
			RETURN COALESCE ( COUNTROWS ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) && VAR Nacimiento = Personas[FechaNacimiento] VAR Valida = NOT ISBLANK ( Nacimiento ) && Nacimiento <= Corte VAR EdadCorte = YEAR ( Corte ) - YEAR ( Nacimiento ) - IF ( FORMAT ( Corte, "MMdd" ) < FORMAT ( Nacimiento, "MMdd" ), 1, 0 ) RETURN IF ( Desde = -1, NOT Valida, Valida && EdadCorte >= Desde && EdadCorte <= Hasta ) ) ), 0 )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Antiguedad media' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN AVERAGEX ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) ), DIVIDE ( DATEDIFF ( Personas[FechaAlta], Corte, DAY ), 365.25 ) )
		formatString: #,0.0
		displayFolder: Indicadores

	measure 'Mujeres en plantilla' =
			CALCULATE ( [Plantilla al cierre], KEEPFILTERS ( Personas[Sexo] = "F" ) )
		formatString: #,0
		displayFolder: Indicadores

	measure 'Mujeres %' =
			DIVIDE ( [Mujeres en plantilla], [Plantilla al cierre] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Cobertura sexo %' =
			VAR Corte = MAX ( Calendario[Fecha] )
			RETURN DIVIDE ( COUNTROWS ( FILTER ( Personas, Personas[FechaAlta] <= Corte && ( ISBLANK ( Personas[FechaBajaEmpresa] ) || Personas[FechaBajaEmpresa] > Corte ) && NOT ISBLANK ( Personas[Sexo] ) && Personas[Sexo] <> "" ) ), [Plantilla al cierre] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Representacion mujeres comparable %' =
			IF ( [Plantilla al cierre] >= 10, [Mujeres %] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Brecha salarial %' =
			VAR F = CALCULATE ( [Personas con salario], REMOVEFILTERS ( Personas[Sexo] ), Personas[Sexo] = "F" )
			VAR H = CALCULATE ( [Personas con salario], REMOVEFILTERS ( Personas[Sexo] ), Personas[Sexo] = "M" )
			VAR SF = CALCULATE ( [Salario medio], REMOVEFILTERS ( Personas[Sexo] ), Personas[Sexo] = "F" )
			VAR SH = CALCULATE ( [Salario medio], REMOVEFILTERS ( Personas[Sexo] ), Personas[Sexo] = "M" )
			RETURN IF ( F >= 8 && H >= 8, DIVIDE ( SH - SF, SH ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Rotacion anterior %' =
			VAR Inicio = MIN ( Calendario[Fecha] )
			VAR Fin = MAX ( Calendario[Fecha] )
			VAR Dias = INT ( Fin - Inicio ) + 1
			VAR Desde = Inicio - Dias
			VAR Cobertura = MINX ( ALL ( Calendario ), Calendario[Fecha] )
			RETURN IF ( Desde >= Cobertura, CALCULATE ( [Rotacion del periodo %], REMOVEFILTERS ( Calendario ), DATESBETWEEN ( Calendario[Fecha], Desde, Inicio - 1 ) ) )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Indicadores

	measure 'Cambio rotacion pp' =
			IF ( NOT ISBLANK ( [Rotacion anterior %] ), ( [Rotacion del periodo %] - [Rotacion anterior %] ) * 100 )
		formatString: +0.0 "pp";-0.0 "pp";0.0 "pp"
		displayFolder: Indicadores

	measure 'Contexto del periodo' =
			"PERIODO · " & FORMAT ( MIN ( Calendario[Fecha] ), "dd/MM/yyyy" ) & " — " & FORMAT ( MAX ( Calendario[Fecha] ), "dd/MM/yyyy" ) & "  |  " & IF ( HASONEVALUE ( Personas[Departamento] ), SELECTEDVALUE ( Personas[Departamento] ), "Varios / todos los departamentos" )
		formatString: General
		displayFolder: Indicadores

	measure 'Lectura ejecutiva' =
			"BALANCE · " & FORMAT ( [Plantilla al inicio], "#,0" ) & " al inicio + " & FORMAT ( [Altas del periodo], "#,0" ) & " altas − " & FORMAT ( [Bajas del periodo], "#,0" ) & " bajas = " & FORMAT ( [Plantilla al cierre], "#,0" ) & " al cierre.  |  Rotación: " & IF ( ISBLANK ( [Rotacion del periodo %] ), "sin base", FORMAT ( [Rotacion del periodo %], "0.0%" ) ) & ". Revisar tasas y tamaño de cada área."
		formatString: General
		displayFolder: Indicadores

	column PersonaID
		dataType: string
		sourceColumn: PersonaID
		summarizeBy: none
	column FechaAlta
		dataType: dateTime
		formatString: Short Date
		sourceColumn: FechaAlta
		summarizeBy: none
	column FechaBajaEmpresa
		dataType: dateTime
		formatString: Short Date
		sourceColumn: FechaBajaEmpresa
		summarizeBy: none
	column Departamento
		dataType: string
		sourceColumn: Departamento
		summarizeBy: none
	column PuestoTrabajo
		dataType: string
		sourceColumn: PuestoTrabajo
		summarizeBy: none
	column Centro
		dataType: string
		sourceColumn: Centro
		summarizeBy: none
	column Sexo
		dataType: string
		sourceColumn: Sexo
		summarizeBy: none
	column FechaNacimiento
		dataType: dateTime
		formatString: Short Date
		sourceColumn: FechaNacimiento
		summarizeBy: none
	column SalarioAnual
		dataType: int64
		formatString: #,0
		sourceColumn: SalarioAnual
		summarizeBy: sum
	column NivelEducativo
		dataType: string
		sourceColumn: NivelEducativo
	column EstadoCivil
		dataType: string
		sourceColumn: EstadoCivil
	column NumeroHijos
		dataType: int64
		sourceColumn: NumeroHijos
		summarizeBy: sum
	column ModalidadTrabajo
		dataType: string
		sourceColumn: ModalidadTrabajo
	column TipoContrato
		dataType: string
		sourceColumn: TipoContrato
	column NivelPuesto
		dataType: string
		sourceColumn: NivelPuesto
	column Provincia
		dataType: string
		sourceColumn: Provincia
	column Nacionalidad
		dataType: string
		sourceColumn: Nacionalidad
	column FechaInicioPuesto
		dataType: dateTime
		formatString: Short Date
		sourceColumn: FechaInicioPuesto
	column JornadaSemanal
		dataType: int64
		sourceColumn: JornadaSemanal
	column Edad = IF ( NOT ISBLANK ( Personas[FechaNacimiento] ), VAR Corte = TODAY () VAR Nacimiento = Personas[FechaNacimiento] RETURN YEAR ( Corte ) - YEAR ( Nacimiento ) - IF ( FORMAT ( Corte, "MMdd" ) < FORMAT ( Nacimiento, "MMdd" ), 1, 0 ) )
		dataType: int64
		isHidden
	column 'Tramo edad' = SWITCH ( TRUE (), Personas[Edad] < 30, "Menos de 30", Personas[Edad] < 40, "30–39", Personas[Edad] < 50, "40–49", Personas[Edad] < 60, "50–59", "60 o más" )
		dataType: string
		isHidden
	column 'Antigüedad años' = DIVIDE ( DATEDIFF ( Personas[FechaAlta], COALESCE ( Personas[FechaBajaEmpresa], TODAY () ), DAY ), 365.25 )
		dataType: int64
		isHidden
	column 'Tramo antigüedad' = SWITCH ( TRUE (), Personas[Antigüedad años] < 1, "Menos de 1 año", Personas[Antigüedad años] < 3, "1–2 años", Personas[Antigüedad años] < 5, "3–4 años", "5+ años" )
		dataType: string
		isHidden
	column 'Tramo salarial' = SWITCH ( TRUE (), ISBLANK ( Personas[SalarioAnual] ) || Personas[SalarioAnual] <= 0, "Sin dato", Personas[SalarioAnual] < 30000, "< 30k", Personas[SalarioAnual] < 40000, "30k–40k", Personas[SalarioAnual] < 50000, "40k–50k", "50k+" )
		dataType: string

	column 'Tramo antiguedad salida' = IF ( ISBLANK ( Personas[FechaBajaEmpresa] ), BLANK (), VAR Meses = DATEDIFF ( Personas[FechaAlta], Personas[FechaBajaEmpresa], DAY ) / 365.25 RETURN SWITCH ( TRUE (), Meses < 1, "01 · Menos de 1 año", Meses < 3, "02 · 1–2 años", Meses < 5, "03 · 3–4 años", "04 · 5+ años" ) )
		dataType: string

	partition Personas = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\PeopleAnalyticsDaxKit\datos-ejemplo\personas.csv"),[Delimiter=",", Columns=19, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Headers,{{"PersonaID", type text},{"FechaAlta", type date},{"FechaBajaEmpresa", type date},{"Departamento", type text},{"PuestoTrabajo", type text},{"Centro", type text},{"Sexo", type text},{"FechaNacimiento", type date},{"SalarioAnual", Int64.Type},{"NivelEducativo", type text},{"EstadoCivil", type text},{"NumeroHijos", Int64.Type},{"ModalidadTrabajo", type text},{"TipoContrato", type text},{"NivelPuesto", type text},{"Provincia", type text},{"Nacionalidad", type text},{"FechaInicioPuesto", type date},{"JornadaSemanal", Int64.Type}}, "en-US")
				in
				    Types
